# Generated by Django 5.2.1 on 2025-06-23 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('unit', models.CharField(max_length=50, verbose_name='Unit')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='supplier.supplier')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'ordering': ['id'],
            },
        ),
    ]
