# Generated by Django 5.2.1 on 2025-06-23 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('stage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='employee.employee')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='stage.stage')),
            ],
            options={
                'verbose_name': 'Employee Assignment',
                'verbose_name_plural': 'Employee Assignments',
                'ordering': ['id'],
                'unique_together': {('employee', 'stage')},
            },
        ),
    ]
