# Generated by Django 5.2.1 on 2025-06-23 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.PositiveIntegerField(verbose_name='Quantity Used')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_usages', to='material.material')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_materials', to='project.project')),
            ],
            options={
                'verbose_name': 'Project Material',
                'verbose_name_plural': 'Project Materials',
                'ordering': ['id'],
                'unique_together': {('project', 'material')},
            },
        ),
    ]
